### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by ranebrown** [JSD915/CSCI2270_FinalProject#1]
There is no documentation on how to run your program.

**Comment by JSD915** [comment]
Sorry, I didn't properly commit the Readme originally. You can follow the instructions there now.
Thanks for letting me know
-Joe

**Comment by ranebrown** [comment]
I'm still not sure what to do when I run the exe. There don't seem to be any instructions on how to play the game.

**Comment by JSD915** [comment]
Just added a help option. Type ? for a list of commands.
