### ISSUE TITLE
No documentation and when I hit 'RUN' it tells me the background info but then gives me no options.

### ISSUE THREAD

**Issue by codytowstik** [JSD915/CSCI2270_FinalProject#2]

**Comment by JSD915** [comment]
the game now has instructions on commands. also documentation of the what functions and classes do has been added to main.cpp and the header files

**Comment by JSD915** [comment]
please let me know if you feel more documentation is necessary.

**Comment by codytowstik** [comment]
Good enough. Mostly just needed that one line you added.
